# -*- coding: utf-8 -*-
"""web_scraping .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WY1DLd_FHjLBTNPWRfNy5xC_YpR-jGWw

# Scraping Data from a Real Website + Pandas
"""

from bs4 import BeautifulSoup
import requests

url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
}

page = requests.get(url, headers=headers)
soup = BeautifulSoup(page.text, 'html.parser')

print(soup)

soup.find_all('table')[1]

soup.find('table', class_='wikitable sortable')

table = soup.find_all('table')[0]

print(table)

world_titles = table.find_all('th')

print(world_titles)

world_table_title = [title.text.strip() for title in world_titles]
print(world_table_title)

import pandas as pd

df = pd.DataFrame(columns = world_table_title)
df

column_data = table.find_all('tr')

for row in column_data[1:]:
  row_data = row.find_all('td')
  individual_row_data = [data.text.strip() for data in row_data]
 # print(individual_row_data)
  length = len(df)
  df.loc[length] = individual_row_data

df

df.to_csv('companies_data.csv', index=False)

from google.colab import files
files.download('companies_data.csv')

